name: release dockerhub
on: [workflow_dispatch]

jobs:
  release_dockerhub:
    name: Dockerhub release
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
